ISAICP-5018: Paragraphs accordion item.
ec-europa/joinup-dev pull request #2223
Opened 2020-08-24 21:43 UTC by idimopoulos

2020-08-26 09:41 UTC, pfrenssen requested changes
Just a small remark, let's test with the facilitator rather than the moderator, the facilitator is a better showcase for this feature.

2020-08-26 09:41 UTC, pfrenssen commented on tests/features/paragraphs/custom_page.paragraphs.feature
> +    Given I am logged in as a moderator
Wouldn't it be better to use the facilitator as the editor of the custom page? I don't think it is a common task for moderators to create content in collections.

2020-08-26 09:41 UTC, pfrenssen commented on tests/features/paragraphs/custom_page.paragraphs.feature
> +    Given I fill in the 1st "Item label" with "Super" in the "Custom page body" field
I like how this is so nicely human readable :+1:

2020-08-26 09:41 UTC, pfrenssen commented on tests/src/Traits/UtilityTrait.php
> +  protected function convertOrdinalToNumber(string $number): int {
Here's the magic :+1:

2020-08-26 10:02 UTC, idimopoulos commented on tests/src/Traits/UtilityTrait.php
> +  protected function convertOrdinalToNumber(string $number): int {
I got that from @brummbar  :D

2020-08-26 14:17 UTC, pfrenssen commented on tests/src/Traits/UtilityTrait.php
> +  protected function convertOrdinalToNumber(string $number): int {
:bear:

2020-08-26 14:21 UTC, pfrenssen reviewed
Is it intentional to give a permission to facilitators to edit Tallinn content?

2020-08-26 14:21 UTC, pfrenssen commented on web/modules/custom/collection/config/install/og.og_role.rdf_entity-collection-facilitator.yml
> +  - 'edit any tallinn_report content'
This seems unrelated to this ticket.

2020-08-27 08:35 UTC, pfrenssen approved these changes
Looking good!

2020-09-03 08:40 UTC, merged