ISAICP-6280: Re-run the update for aliases.
ec-europa/joinup-dev pull request #2319
Opened 2020-11-11 08:40 UTC by idimopoulos

2020-11-18 13:22 UTC, claudiu-cristea requested changes

2020-11-18 13:22 UTC, claudiu-cristea commented on web/modules/custom/joinup_core/joinup_core.install
> -function joinup_core_requirements($phase): array {
Why deleting `joinup_core_requirements()`?

2020-11-25 07:47 UTC, idimopoulos commented on tests/features/collection/propose.feature
> +      | Title | About this group                                               |
I have created a follow up for this. This can be fixed relatively easily upstream in pathauto. You can check ISAICP-6288.

2020-12-02 08:43 UTC, claudiu-cristea approved these changes

2020-12-02 10:27 UTC, merged