ISAICP-5951: Subscription report
ec-europa/joinup-dev pull request #2411
Opened 2021-02-26 20:18 UTC by pfrenssen

2021-03-05 14:10 UTC, pfrenssen commented on web/modules/custom/joinup_subscription/joinup_subscription.routing.yml
> -
This was moved up to maintain alphabetical ordering.

2021-03-05 14:32 UTC, pfrenssen commented on web/profiles/joinup/src/Form/SolutionsByLicenceForm.php
> +    $total = $result->total->getValue();
This is an unrelated bugfix. This caused a random failure during development of this PR.

2021-03-05 14:33 UTC, pfrenssen commented on composer.json
> +        "ext-pdo": "*",
We're already using PDO but this was not declared in the Composer manifest. PHPStorm was complaining about this.

2021-03-08 22:43 UTC, idimopoulos requested changes

2021-03-09 08:39 UTC, pfrenssen commented on web/modules/custom/joinup_group/src/Entity/GroupTrait.php
> +    assert(is_subclass_of($this, ContentEntityBase::class), __TRAIT__ . ' is intended to be used in bundle classes for content entities.');
Good catch! This is probably originated from copy / pasting some other method and I forgot to update the message.

2021-03-11 08:36 UTC, merged