ISAICP-6381: Show the topics with hierarchy.
ec-europa/joinup-dev pull request #2476
Opened 2021-05-19 12:18 UTC by idimopoulos

2021-05-25 20:12 UTC, claudiu-cristea requested changes
I had to reject because this looks very bad:

<img width="1397" alt="Screenshot 2021-05-25 at 22 58 06" src="https://user-images.githubusercontent.com/473868/119562005-8946a680-bdae-11eb-821b-fac9fea302a7.png">

2021-05-27 14:28 UTC, idimopoulos commented on config/sync/search_api.index.published.yml
> +        - meta_entity
I saw today that I had a newer version of the facets installed on my machine which was causing some strange behavior. I think this was the culprit. Now it shows fine for me too.

2021-05-31 11:59 UTC, claudiu-cristea requested changes
I'm requesting to extend the test coverage.

2021-05-31 11:59 UTC, claudiu-cristea commented on tests/features/joinup_search/search.feature
> +      | • Statistics and Analysis (1) |
1. If I'm not missing something, the following statement is true:
   > The sum of child term counts equals the parent term count.
   
   But we need a regression test for this. Preferable to test more than one parent with many child terms.
1. We need also to add a test that asserts search result on 2-3 child terms, then the search results when filtering on parent. The test should prove that all the search entries of child terms are the same as results on parent term. Order is also important.

2021-06-16 11:09 UTC, merged