ISAICP-6467: Do not show the Translate button to edit pages
ec-europa/joinup-dev pull request #2494
Opened 2021-06-08 13:23 UTC by idimopoulos

2021-06-10 08:30 UTC, claudiu-cristea requested changes
I have one question and a request to expand the tests

2021-06-10 08:30 UTC, claudiu-cristea commented on config/sync/block.block.webtools_etrans.yml
> +    pages: "/node/*/edit\r\n/node/*/delete\r\n/rdf_entity/*/edit\r\n/rdf_entity/*/delete\r\n/taxonomy_term/*/edit\r\n/taxonomy_term/*/delete"
Wouldn't it be more exact to use the route filter?

```yaml
- entity.node.edit_form
- entity.node.delete_form
- ...
```

2021-06-10 08:30 UTC, claudiu-cristea commented on tests/features/machine_translation.feature
> +    Then I should not see any Webtools eTrans elements
I see we're banning also the entity delete forms, then why aren't we testing that too?

2021-06-10 19:21 UTC, claudiu-cristea commented on config/sync/block.block.webtools_etrans.yml
> +      10: entity.taxonomy_term.delete_form
This looks like a bug in the route condition module. My guess is that, when exploding the blob, an `array_values()` is missing.

2021-06-14 15:53 UTC, pfrenssen requested changes

2021-06-14 15:53 UTC, pfrenssen commented on tests/src/Traits/EntityTrait.php
> +      'contact_information' => 'rdf_entity',
This method should take human readable aliases, so there should not be any underscores here.

2021-06-15 07:39 UTC, pfrenssen approved these changes

2021-06-18 07:10 UTC, merged