ISAICP-6563: Disable bullet/numbered lists and block quote from the Abstract's toolbar.
ec-europa/joinup-dev pull request #2525
Opened 2021-07-15 20:53 UTC by saidatom

2021-07-16 13:58 UTC, pfrenssen requested changes
This is looking good but it lacks tests. I will add them, I saw that our coverage of the editor can use some attention.

2021-07-16 13:58 UTC, pfrenssen commented on config/sync/user.role.authenticated.yml
> +  - 'use text format abstract_html'
@saidatom do you agree to rename this to `simple_html`? Or some other suggestion?

2021-07-16 14:01 UTC, saidatom commented on config/sync/user.role.authenticated.yml
> +  - 'use text format abstract_html'
@pfrenssen yes `simple_html` sounds good.

2021-07-16 14:03 UTC, saidatom commented on config/sync/filter.format.abstract_html.yml
> +      allowed_view_modes: {  }
With `status: false` is not showing.

2021-07-22 12:09 UTC, pfrenssen commented on config/sync/user.role.authenticated.yml
> +  - 'use text format abstract_html'
Argh `simple_html` is already taken! Going to go for `essential_html`.

2021-07-27 08:10 UTC, saidatom commented
Looks good. Approved.

2021-07-28 06:11 UTC, merged